### ISSUE TITLE
Setup girder

### ISSUE THREAD

**Issue by satra** [dandi/infrastructure#3]
- [ ] create a deployment repo 
- [ ] enable automated redeploy
- [ ] enable database backup and restore
- [ ] Github oauth

**Comment by satra** [comment]
https://github.com/dandi/infrastructure/wiki/Girder-setup-on-aws

**Comment by yarikoptic** [comment]
Work is ongoing in https://github.com/dandi/dandiarchive

**Comment by yarikoptic** [comment]
I think this issue could be closed, we have girder running and specific issues sound be filled against dandiarchive
